#!/usr/bin/with-contenv bash

# Check to ensure VPN configuration is present
if [ ! -e "/config/$OVPNCONF" ]; then
    echo "Could not find requested VPN file: $OVPNCONF"
    exit 1
fi

# Configure IPTables
iptables -F # Flush existing chain
iptables -X # Delete existing user rules
iptables -t nat -F # Flush existing NAT rules"
iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE # Enable NAT
iptables -A INPUT -p tcp --dport 80 -j ACCEPT -m comment --comment "Allow TCP access to GUI port"
iptables -A INPUT -i lo -m comment --comment "Allow inbound loopback" -j ACCEPT
iptables -A OUTPUT -o lo -m comment --comment "Allow outbound loopback" -j ACCEPT
iptables -I INPUT -i eth0 -m comment --comment "In from LAN" -j ACCEPT
iptables -I OUTPUT -o tun+ -m comment --comment "Out to VPN" -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp --dport $OVPNPORT -m comment --comment "Allow OpenVPN traffic" -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp --dport 123 -m comment --comment "Allow NTP" -j ACCEPT
iptables -A OUTPUT -p udp --dport 67:68 -m comment --comment "Allow DHCP" -j ACCEPT
iptables -A OUTPUT -o eth0 -p udp --dport 53 -m comment --comment "Allow DNS" -j ACCEPT
iptables -A FORWARD -i tun+ -o enp1s0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i eth0 -o tun+ -m comment --comment "LAN out to VPN" -j ACCEPT
iptables -P FORWARD DROP
